=head1 Boogie Woogie

Plack/PSGI framework JFF (Just For Fun!).

Three reasons why I wrote it:

=head2 Everybody does it

=head2 It is easy

=head2 It is fun

=head1 Features

=head2 Heavy use of L<Plack> internals, no wheel reinventing

=head2 Reasonable dependencies

=head2 OOP approach with no hacking

=head2 Cool name

=head1 Warning

I don't expect anyone to use it. But it could be another example how to use
L<Plack>/L<PSGI> and build your own framework with the only features that you
need.

=head1 Usage

Create your app:

    package MyApp;
    use Boose;

    extends 'BoogieWoogie';

    sub startup {
        my $self = shift;

        my $r = $self->dispatcher->router;
        $r->add_route('/', defaults => 'foo#bar');
    }

    1;

Create a C<my_app.psgi> file:

    use Plack::Builder;

    use MyApp;

    my $app = MyApp->new;

    builder {
        enable "Plack::Middleware::Static",
          path => qr{\A/favicon.ico\z},
          root => 'htdocs/';

        enable "SimpleLogger", level => "debug";

        $app;
    };

Run it:

    plackup my_app.psgi
